export const CONTACTS_FETCH = 'CONTACTS_FETCH';
export const CONTACTS_SUCCESS = 'CONTACTS_SUCCESS';
export const CONTACTS_ERROR = 'CONTACTS_ERROR';
export const CONTACTS_SHOULD_FETCH = 'CONTACTS_SHOULD_FETCH';
export const CONTACTS_STORAGE_SUCCESS = 'CONTACTS_STORAGE_SUCCESS';
export const CONTACTS_STORAGE_ERROR = 'CONTACTS_STORAGE_ERROR';
